### ISSUE TITLE
summary and index of your bachelor's thesis,

### ISSUE THREAD

**Issue by mbujosab** [Diana-ash/Indicador-Adelantado-LDHR#1]
Dear Diana,

To facilitate access to the summary and index of your bachelor's thesis, please upload it in PDF format (or even better, in plain text).

Thank you,
Diana

**Comment by Diana-ash** [comment]
Dear Marcos, 
Yes, I have just uploaded the summary in PDF format, so it is possible to preview the file. 

Kind regards
